### ISSUE TITLE
Add fdiv/fsqrt instructions to the test generator in SeqFPU 

### ISSUE THREAD

**Issue by ccelio** [ucb-bar/riscv-torture#1]
Currently, the torture generator does not generate fdiv or fsqrt instructions (even though the default riscv gcc compiler behavior is to generate fdiv/fsqrt instructions). 

Preferably, a config option to disable or even choose the instruction mix of fdiv and fsqrt instructions would be provided.

The changes should mainly be to the file `generator/src/main/scala/SeqFPU.scala`.

**Comment by aswaterman** [comment]
Like the other configuration parameters, I think these options would best be exposed as probabilities, rather than booleans.

**Comment by ccelio** [comment]
Agreed.
