### ISSUE TITLE
riscv-torture : make igentest not completing

### ISSUE THREAD

**Issue by duncgrah** [ucb-bar/riscv-torture#14]
I have installed and built all the required packages on a Ubuntu 64-bit machine. When I execute the 'make igentest' to run a single torture test on spike it does not return. I wonder if I am doing something wrong or how to investigate?

_riscv-torture$ make igentest
java -Xmx1G -Xss8M -XX:MaxPermSize=128M -jar sbt-launch.jar 'testrun/run'
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=128M; support was removed in 8.0
[info] Loading project definition from /home/graham/git/riscv-torture/project
[info] Set current project to torture (in build file:/home/graham/git/riscv-torture/)
[info] Running torture.testrun.TestRunner 
Physical mode
running:List(spike, +signature=output/test.spike.sig, output/test)_

When I look in the output directory I can see that a test.S and test have bee created. When trying to execute this directly with spike I get a trap_instruction_access_fault
_riscv-torture$ spike -l output/test
core   0: 0x0000000000001000 (0x00000297) auipc   t0, 0x0
core   0: 0x0000000000001004 (0x02028593) addi    a1, t0, 32
core   0: 0x0000000000001008 (0xf1402573) csrr    a0, mhartid
core   0: 0x000000000000100c (0x0182b283) ld      t0, 24(t0)
core   0: 0x0000000000001010 (0x00028067) jr      t0
core   0: 0x0000000080002000 (0x00000000) addi    s0, sp, 0
core   0: exception trap_illegal_instruction, epc 0x0000000080002000
core   0:           badaddr 0x0000000000000000_

I saw from the test disassembly that the 'start' address is 0x80000000, so trying to start from this address  the execution starts but then I hit probably a system access and it stops ...
_riscv-torture$ spike -l --pc=0x80000000 output/test
core   0: 0x0000000000001000 (0x00000297) auipc   t0, 0x0
core   0: 0x0000000000001004 (0x02028593) addi    a1, t0, 32
core   0: 0x0000000000001008 (0xf1402573) csrr    a0, mhartid
core   0: 0x000000000000100c (0x0182b283) ld      t0, 24(t0)
core   0: 0x0000000000001010 (0x00028067) jr      t0
core   0: 0x0000000080000000 (0x04c0006f) j       pc + 0x4c
core   0: 0x000000008000004c (0xf1402573) csrr    a0, mhartid
core   0: 0x0000000080000050 (0x00051063) bnez    a0, pc + 0
...
core   0: 0x0000000080000044 (0xfdcf2023) sw      t3, -64(t5)
core   0: 0x0000000080000048 (0xff9ff06f) j       pc - 0x8
core   0: 0x0000000080000040 (0x00001f17) auipc   t5, 0x1
core   0: 0x0000000080000044 (0xfdcf2023) sw      t3, -64(t5)_

So deciding that I need to invoke using PK I get 
_riscv-torture$ spike pk output/test
couldn't open ELF program: output/test!_

Can anyone help? Sure this is just not understanding something but cannot find the information I need.
Thanks

**Comment by CLappin** [comment]
Hi,

There is a possability that the torture test is out of date with the rocket core.  
https://forums.sifive.com/t/riscv-torture-test/820

Regards,
Ciaran

**Comment by ccelio** [comment]
The env submodule needs to be bumped to master.
