### ISSUE TITLE
RV32I support?

### ISSUE THREAD

**Issue by cliffordwolf** [ucb-bar/riscv-torture#6]
I'd like to use riscv-torture to generate RV32I / RV32IC test cases (for PicoRV32). Are the 32 bit ISAs supported? What set of config file options would I use to generate RV32I code? Thanks!

**Comment by ccelio** [comment]
Hey Clifford,

To get only the I-subset, just turn off the appropriate flags in the config file (https://github.com/ucb-bar/riscv-torture/blob/master/config/default.config).  You only need to touch the first 16 lines. It's... not the most obvious, but we accept pull requests. ;)

As for 32-bit? Haven't really looked into it, but torture is set up to mirror the riscv-tests repository, and uses the same riscv-tests-env sub repository to change the "test machine environment".  The compilation is performed in (https://github.com/ucb-bar/riscv-torture/blob/master/testrun/src/main/scala/main.scala), for some reason, so you should just have to modify that slightly to get what you want.  

Again, we accept pull requests, if you'd like to clean this up, pull the compile strings to a higher level, and make it a config option. =)

**Comment by cliffordwolf** [comment]
Thanks Christopher,

unfortunately I'm not a scala programmer, and after trying for an hour just to figure out how to get "lw" instead of "ld" insns in xreg_init (with the proper xreg_init_data memory layout) without success I give up now. Besides what you say about the "test machine environment", the test code generator does not seem to support 32 bit at all and I can't find anything in the code that looks like a proper abstraction for that. It would have been nice using riscv-torture in the PicoRV32 test bench, but sadly I simply can't spare the time that would be required to learn enough Scala and add 32 bit support to riscv-torture..

**Comment by ccelio** [comment]
Yah, I didn't realize how engrained the 64b-ness was within torture's code generation, but this is totally salvageable. 

I'd start be grepping through the code for "sd/SD/ld/LD/dword/addr_d/", and start making manually changes (e.g., ld->lw, etc.) as required until you can get it to no longer emit any RV64I. Then, get the program to run properly in Spike.  Then, take a step back and figure out how to abstract the changes. The first two steps really shouldn't be that bad; you don't have to write any Scala code... just delete it or find and replace! And there's already flags to turn off AMOs, etc., so even the last step shouldn't be too onerous. 

For example, to get xreg_init to use "lw", is probably something like just changing this line of code:

https://github.com/ucb-bar/riscv-torture/blob/master/generator/src/main/scala/HWRegPool.scala#L89

``` scala
class XRegsPool extends ScalarRegPool
{
  val (name, regname, ldinst, stinst) = ("xreg", "reg_x", "lw", "sw")
```

XRegsPool extends ScalarRegPool means it's going to add all of the code in `trait ScalarRegPool` into XRegsPool (basically inheriting all of its stuff).  I think. I dunno, I never learned Scala myself.

Torture is going to find your bugs and spending a weekend on it can pay dividends later.

**Comment by cliffordwolf** [comment]
Thanks! This was indeed helpful. I now have a patch that seems to create correct RV32I test cases:

https://github.com/cliffordwolf/picorv32/blob/master/scripts/torture/riscv-torture-rv32.diff

I'm assuming there is more to do for full RV32G support, but that is not my problem.. :) Feel free to use that patch as basis for adding a proper RV32 config switch to riscv-torture. At least for now I think I'm quite happy with just using that patch for my application..

Thanks again. I'm closing the issue since I think I got all the help I need from you guys..
